services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-stcms
    restart: always
    ports:
      - "${SERVER_DEV_PORT:-3000}:3000"
    environment:
      # We override the URI to point to the 'mongo' container
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/stcms-db?authSource=admin
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_LASTNAME: ${ADMIN_LASTNAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: db-stcms
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
